### ISSUE TITLE
Is the data exchange between pyFR and Catalyst directedly?

### ISSUE THREAD

**Issue by lj-cug** [vincentlab/PyFR-Catalyst#14]
Dear Sir:
    These days I consider the live visualization for my CUDA code, and I notice your project. Is the data exchanged between pyFR and VTK (Catalyst) not through CPU memory? 
Thanks!
Li Jian

**Comment by FreddieWitherden** [comment]
Data is exchanged directly from PyFR on the GPU to VTK-m on the GPU without copying anything through CPU memory.
